### ISSUE TITLE
thread_info.php never showing

### ISSUE THREAD

**Issue by karolyipeter** [5agado/conversation-analyzer#11]
Hello!

My browser never makes requests to thread_info.php when browsing messenger messages. Is there a new POST url I should watch out for? I found some post messages, but it's not clear which cookie I should use and I couln't get it to work with either.

Any help would be appreciated :)

**Comment by 5agado** [comment]
Facebook frequently changes the way messages are retrieved, and seems this time they implemented a major change which will required some work for the scraper to work again.

I will update the README to make sure this is pointed out more clearly, plus will create an issue regarding this. If anybody will pick it up, good, otherwise will have to wait until I find some time to fix it myself.
