### ISSUE TITLE
Update scraper based on Facebook new message-retrieval mechanism

### ISSUE THREAD

**Issue by 5agado** [5agado/conversation-analyzer#12]
Message retrieval for Facebook doesn't call anymore *thread_info.php* and POST call itself changed in term of parameters sent and mechanism to specify offset, data and quantity.

Need to update the now broken *conversationScraper.py* to reflect this changes.

**Comment by landalex** [comment]
I was interested in using the iPython notebooks you made for some statistics of my own, so I published a [little script](https://github.com/landalex/facebook-message-converter) that converts message archives downloaded from Facebook to the format your scraper/parser uses. If you'd like me to make a PR adding the script to the repo or otherwise integrating this into your scraper/parser, let me know.

**Comment by 5agado** [comment]
Hi @landalex , that sounds great.
I still have to try out the new download option for Facebook, but in the meanwhile you can definitely create a PR to add your script to this repo utils.
Be sure to put your info in the file and possibly some comments for the code, then I will try it out before merging it.
